
GET http://localhost:4047/

###
POST http://localhost:4047/create
Content-Type: application/json

{
    "email": "leohencosta18@gmail.com",
    "senha": "denver12@",
    "numeroTel": "92992345446"
}

###
POST http://localhost:4047/update
Content-Type: application/json

{
    "email": "leohencosta18@gmail.com",
    "senha": "denver12@",
    "numeroTel": "92992345446",
    "seguimento": "Tecnologias"
}