
GET http://localhost:4047/

###
POST http://localhost:4047/create
Content-Type: application/json

{
    "email": "leohencosta18@gmail.com",
    "senha": "denver12@",
    "numeroTel": "92992345446"
}

###
POST http://localhost:4047/update
Content-Type: application/json

{
    "email": "leohencosta18@gmail.com",
    "senha": "denver12@",
    "numeroTel": "92992345446",
    "ID": "219747a4-eec6-4dd3-8a3a-82d43af38dbd"
}